### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN api.stripe.com:443

### ISSUE THREAD

**Issue by yujia917** [stripe/stripe-ios#1416]
Hi:

I got this error when trying to call any Stripe API in IOS. 

{ Error: An error occurred with our connection to Stripe.
    at /srv/node_modules/stripe/lib/StripeResource.js:211:9
    at ClientRequest.req.on (/srv/node_modules/stripe/lib/StripeResource.js:407:67)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  raw: 
   { message: 'An error occurred with our connection to Stripe.',
     detail: 
      { Error: getaddrinfo EAI_AGAIN api.stripe.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
        errno: 'EAI_AGAIN',
        code: 'EAI_AGAIN',
        syscall: 'getaddrinfo',
        hostname: 'api.stripe.com',
        host: 'api.stripe.com',
        port: '443' } },
  rawType: undefined,
  code: undefined,
  param: undefined,
  detail: 
   { Error: getaddrinfo EAI_AGAIN api.stripe.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.stripe.com',
     host: 'api.stripe.com',
     port: '443' },
  headers: undefined,
  requestId: undefined,
  statusCode: undefined }

**Comment by krunvaghela** [comment]
@yujia917 How you Solved It ?
